# Generated by Django 2.0 on 2020-09-30 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_level', models.CharField(blank=True, max_length=255, null=True)),
                ('instrument', models.CharField(blank=True, max_length=255, null=True)),
                ('student_since', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('birthday', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'studenttt',
                'db_table': 'tbl_studenttt',
                'managed': True,
            },
        ),
    ]
