# Generated by Django 2.0 on 2020-09-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201001_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
